### PR TITLE
From Chris- creating first pull request with a test file (on AAE-Legal Agent status topic)

### PR DESCRIPTION
**Pull request by CryptosOdysseus**
[Note on Inventor-AAE and its Legal Agent status .md.txt](https://github.com/dazzaji/AutomatedLegalEntityChallenge/files/3472647/Note.on.Inventor-AAE.and.its.Legal.Agent.status.md.txt)

### CODE REVIEW

**Comment by dazzaji** [comment]
Can you add a creative commons license to this file please?

**Comment by CryptosOdysseus** [comment]
[Note on Inventor-AAE and its Legal Agent status .md .txt](https://github.com/dazzaji/AutomatedLegalEntityChallenge/files/3477187/Note.on.Inventor-AAE.and.its.Legal.Agent.status.md.txt)
Hereby enclosing updated file with added creative commons license, as per your request. Thank you.

**Comment by dazzaji** [comment]
Merged

**Comment by CryptosOdysseus** [comment]
OK

**Comment by dazzaji** [comment]
hmmm.... it doesn't look as though the file merged.  i think there was something wonky about the pull request.  maybe you put the file into the comments instead of making the pull request to merge the file itself?  i can look into this and try to troubleshoot.

**Comment by CryptosOdysseus** [comment]
Right- I merely dropped the updated file in above comment box, instead of doing a new pull request for that updated file (noted this is needed). And just now I attempted a new pull request, however not going through this time. Will try again.

**Pull request merged**
